nnstreamer: add missing flatbuffers dependency
Add the missing dependency flatbuffers. This is needed to avoid the
following compiling error:

```
error: static assertion failed: Non-compatible flatbuffers version included
```

Based on: https://github.com/nxp-imx/meta-imx/blob/219f6d04a4c339eb6f2dc626f944bbdf9a716ff5/meta-imx-ml/recipes-nnstreamer/nnstreamer/nnstreamer_2.4.0.bb#L80

Signed-off-by: Bruno Bonaldi Teixeira <bruno.t@variscite.com>